-- Generate SQL to drop foreign key constraints if they exist

SELECT CONCAT('
IF EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
    WHERE TABLE_SCHEMA = ''dbo''
      AND TABLE_NAME = ''', TABLE_NAME, '''
      AND CONSTRAINT_NAME = ''', CONSTRAINT_NAME, '''
)
BEGIN
    ALTER TABLE ', TABLE_NAME, '
    DROP CONSTRAINT ', CONSTRAINT_NAME, ';
END;'
)
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
WHERE CONSTRAINT_TYPE = 'FOREIGN KEY';