

SELECT  
      QUOTENAME(SCHEMA_NAME(sOBJ.schema_id)) +'.' + QUOTENAME(sOBJ.name) AS [TableName]  
      , SUM(sdmvPTNS.row_count) AS [RowCount]  
FROM  
      sys.objects AS sOBJ  
      INNER JOIN sys.dm_db_partition_stats AS sdmvPTNS  
            ON sOBJ.object_id = sdmvPTNS.object_id  
WHERE   
      sOBJ.type ='U'  
      AND sOBJ.is_ms_shipped = 0x0  
      AND sdmvPTNS.index_id < 2  AND 
	  sOBJ.name IN ('RES_SERVICE_DOMAIN_LOOKUP',
'RES_SERVICE_CATEGORY_LOOKUP',
'RES_SERVICE_LOOKUP',
'RES_REF_LOOKUP_CATEGORY',
'RES_REF_LOOKUP',
'RES_REGION_LOOKUP',
'RES_CITY_LOOKUP',
'RES_ENTITY_ROLE_LOOKUP',
'RES_REACT_EXCLUDED_DOC_LIST',
'RES_SITE_LOOKUP',
'RES_SERVICE_SUPPORT_DATA',
'RES_ADMIN_REJECT_REASON',
'RES_ADMIN_RETURN_REASON',
'RES_APPOINTMENT_SLOT_LOOKUP',
'RES_FACILITY_RATINGS_JUNCTION',
'RES_FACILITY_RATINGS_LOOKUP',
'RES_FACILITY_SERVICETYPE_CATEGORY_LOOKUP',
'RES_FACILITY_SERVICETYPE_LOOKUP',
'RES_FACILITY_TYPE_CATEGORY_LOOKUP',
'RES_FACILITY_TYPE_LOOKUP',
'RES_FACILITY_TYPE_SUBCATEGORY_LOOKUP',
'RES_FACILITY_UNITS_JUNCTION',
'RES_FACILITY_UNITS_LOOKUP',
'RES_LICENSE_DURATION_JUNCTION',
'RES_LICENSE_DURATION_LOOKUP',
'RES_WORKFLOW_STEP_LOOKUP',
'RES_SERVICE_FEES',
'RES_MULTILINGUAL',
'RES_NOTIFICATION_TEMPLATE',
'RES_SERVICE_ISIC_CODE')
GROUP BY  
      sOBJ.schema_id  
      , sOBJ.name  
ORDER BY [TableName] ;